INSERT INTO preguntas (Pregunta) VALUES 
	("Fruta que por fuera es verde"),
	("¿Que se le puede hacer al piso?"),
	("¿Algo que prendes y apagas todos los dias?"),
	("Ademas del pollo, menciona otra ave que se coma"),
	("Problema que te puede pasar cuando estas en el WC/Baño"),
	("Regalo de bodas mas comun de recien casados"),
	("Comida mexicana mas popular"),
	("Parte del cuerpo en donde los dolores son mas frecuentes"),
	("Menciona algo opuesto a la libertad"),
	("Propositos de año nuevo"),
	("Platillo tipico para la cena de navidad"),
	("Cuando sus hijas les dicen que ya tienen novio, a que le temen algunos papas"),
	("Si tu pareja te dijera {Vamos a lo obscurito} ¿A donde crees que te llevaria?"),
	("Articulo de uso personal que ubiera sido muy util en la epoca de los cabernicolas"),
	("Menciona un pariente del pato donald"),
	("Fraces que le dices a alguien en su cumpleaños"),
	("¿Que animales pueden tener dentro de una pesera?"),
	("Menciona un objeto por lo que hermanos adolecentes puedan peliarse"),
	("Otra manera de decirle al dinero"),
	("¿Que no puedes meter a una galeria o museo?");


INSERT INTO respuestas (id_Pregunta, Respuesta, Puntos) VALUES
	(1, "Pera", 38),
	(1, "Manzana", 26),
	(1, "Sandia", 22),
	(1, "Limón", 14),
	(2, "Pulirlo", 40),
	(2, "Trapearlo", 37),
	(2, "Encerarlo", 15),
	(2, "Barrerlo", 8),
	(3, "Luz", 38),
	(3, "Television", 26),
	(3, "Computadora", 15),
	(3, "El radio/Estereo", 11),
	(4, "Guajolote/Pavo", 48),
	(4, "Pato", 23),
	(4, "Codorniz", 14),
	(4, "Gallina", 8),
	(5, "Se acabo el papel", 41),
	(5, "Estar estreñido", 27),
	(5, "No hay agua", 13),
	(5, "Esta tapado el excusado", 10),
	(5, "No alcanzar a llegar", 9),
	(6, "Vajilla", 34),
	(6, "Liquadora", 29),
	(6, "Toallas", 21),
	(6, "Plancha", 15),
	(7, "Tacos", 41),
	(7, "Pozole", 19),
	(7, "Enchiladas", 18),
	(7, "Quesadillas", 9),
	(8, "Cabeza", 45),
	(8, "Estomago/Vientre", 29),
	(8, "Espalda", 17),
	(8, "Piernas", 9),
	(9, "Esclavitud", 49),
	(9, "Encierro", 31),
	(9, "Prision", 11),
	(9, "Opresion", 9),
	(10, "Hacer dieta", 33),
	(10, "Hacer ejercicio", 27),
	(10, "Ahorrar", 17),
	(10, "Dejar de fumar", 14),
	(10, "Comprar algun articulo", 9),
	(11, "Pavo", 39),
	(11, "Bacalao", 32),
	(11, "Romeritos", 12),
	(11, "Lomo/Pierna", 11),
	(11, "Ensalada de manzana", 6),
	(12, "Embarazo", 46),
	(12, "Sexo", 13),
	(12, "Casarse", 8),
	(12, "Abusen", 6),
	(12, "Que sea un mal hombre", 4),
	(13, "Hotel", 45),
	(13, "Casa", 20),
	(13, "Parque", 12),
	(13, "Callejon", 10),
	(13, "Cine", 9),
	(13, "Auto", 4),
	(14, "Shampoo", 40),
	(14, "Jabon", 17),
	(14, "Rastrillo", 5),
	(14, "Ropa", 5),
	(14, "Pasta dental", 5),
	(14, "Perfume", 5),
	(14, "Desodorante", 3),
	(15, "Daisy", 26),
	(15, "Tio rico MC Pato", 22),
	(15, "Sobrino Hugo", 14),
	(15, "Sobrino Luis", 13),
	(15, "Sobrino Paco", 10),
	(16, "Felicidades", 49),
	(16, "Feliz cumpleaños", 39),
	(16, "Que la pases bien", 5),
	(16, "Feliz dia", 4),
	(16, "Que cumplas mucho mas", 3),
	(17, "Peces", 33),
	(17, "Tortugas", 20),
	(17, "Serpientes/Viboras", 18),
	(17, "Iguanas", 9),
	(17, "Ranas", 7),
	(18, "Ropa", 33),
	(18, "Zapatos", 14),
	(18, "Television/Control tv", 9),
	(18, "Computadora", 6),
	(18, "Baño", 5),
	(19, "Lana", 29),
	(19, "Billete", 21),
	(19, "Varo", 10),
	(19, "Feria", 8),
	(19, "Plata", 6),
	(20, "Comida", 46),
	(20, "Camara fotografica", 22),
	(20, "Animales/Mascotas", 21),
	(20, "Bebidas", 5);